### ISSUE TITLE
Unzipper misses entry

### ISSUE THREAD

**Issue by jakobholmelund** [augustl/js-unzip#1]
Hi august.. I have a problem.. For some unexplained reason the unzipper misses an entry in my epub file.. It reads the mimetype and the META-INF dir just fine, but when it comes to the dir OEBPS it just skips it and thus js-epub fails.. I hope there is a logical explanation hope you can help

Regards

Jakob

**Comment by augustl** [comment]
Hey!

I just deprecated this project. I was looking into fixing bugs and updating it, but I found a much better alternative that didn't exist when I created this project. Check it out :)

https://gildas-lormeau.github.io/zip.js/
