### ISSUE TITLE
readEntries not working if my zip file contains one xml file and .moc file

### ISSUE THREAD

**Issue by Harsha12345678** [augustl/js-unzip#10]
I have zipped one xml file and one .moc file. .moc is our project specific extension but actually content inside adhers to xml format.

In my application I get the url of this zip file hosted on network, I tried to use ajax call with GET to get the content from WEB url in blob object.

If I input this blob object for JSUnzip API and followed by that I am checking the number of entries.

If the ZIP file contains only xml file it is getting the entries properly but if mocf file is present in the zip it is not working.

1) Any specific reasons why few file formats not supported?

2) For a zip with xml file alone I got the entry properly but if I give that as input for inflate  uncompressed = JSInflate.inflate(entry.data); (where entry = unzipper.entries[0]). I am getting uncompressed data as empty.

i.e. inflate is resulting empty data.

Please review and suggest your opinion.

**Comment by augustl** [comment]
Hey!

I just deprecated this project. I was looking into fixing bugs and updating it, but I found a much better alternative that didn't exist when I created this project. Check it out :)

https://gildas-lormeau.github.io/zip.js/
