### ISSUE TITLE
entries.lengh is always 1

### ISSUE THREAD

**Issue by Luluqz** [augustl/js-unzip#12]
Hello,
I'm working out with test/integration/index.html & test/integration/test.js

I don't know why but entries.lengh is always equal to 1, even if the zip contains multiples files.

Can you help?

Thanks!

**Comment by augustl** [comment]
Hey!

I just deprecated this project. I was looking into fixing bugs and updating it, but I found a much better alternative that didn't exist when I created this project. Check it out :)

https://gildas-lormeau.github.io/zip.js/
