### ISSUE TITLE
regression for js-unzip.js of Nov 6th

### ISSUE THREAD

**Issue by casaschi** [augustl/js-unzip#3]
Tried updating js-unzip.js with the new release of Nov 6th and my page does not work anymore, the unzip process does not seem to ever end.

The page worked fine with the previous version of js-unzip, PROVIDED I ADDED THE "& 0xFF" JSUnzip.BigEndianBinaryStream.getByteAt

I tried debugging, but even after a relative long time (much longer that required for the older js-unzip.js to display the page) google chrome is still stuck in loops in js-unzip/js-inflate.

This is the page:
http://pgn4web.casaschi.net/zipped.html
This is the zipfile I'm trying to open:
http://pgn4web.casaschi.net/zipped.zip

**Comment by augustl** [comment]
Hey!

I just deprecated this project. I was looking into fixing bugs and updating it, but I found a much better alternative that didn't exist when I created this project. Check it out :)

https://gildas-lormeau.github.io/zip.js/
