### ISSUE TITLE
Issue: js-unzip stops on PNG / Supported file formats

### ISSUE THREAD

**Issue by askmatey** [augustl/js-unzip#4]
PNGs seems to be supported, but it's not possible to read a ZIP archive with several images or a mixed one (textfiles + png's). The process stops, if the first file is PNG or does not read PNG, if the first file(s) are no images.

Are png/gif images fully supported in *js-unzip* ? 

![screenshot](http://www.bilderload.com/daten/screenshotBJPST.png)

    for (var i = 0; i < unzipper.entries.length; i++) {

        var entry = unzipper.entries[i];
        console.log(entry);
    }
    }

**Comment by augustl** [comment]
Hey!

I just deprecated this project. I was looking into fixing bugs and updating it, but I found a much better alternative that didn't exist when I created this project. Check it out :)

https://gildas-lormeau.github.io/zip.js/
