### ISSUE TITLE
Not support Zip file

### ISSUE THREAD

**Issue by techzhou** [augustl/js-unzip#7]
simple use
when I run "unzipper.readEntries();"
got error "Uncaught File is using bit 3 trailing data descriptor. Not supported. "

what meaning?

**Comment by augustl** [comment]
Hey!

I just deprecated this project. I was looking into fixing bugs and updating it, but I found a much better alternative that didn't exist when I created this project. Check it out :)

https://gildas-lormeau.github.io/zip.js/
